-- Seed Data: Test Embeddings and Semantic Memories
-- Purpose: Create sample embedding data for development/testing
-- Environment: Development/Test only
-- Note: Actual embeddings are 1536-dimensional vectors (OpenAI text-embedding-3-small)

DO $$
DECLARE
    v_alice_id UUID;
    v_bob_id UUID;
    v_sample_embedding vector(1536);
BEGIN
    SELECT id INTO v_alice_id FROM users WHERE username = 'alice' LIMIT 1;
    SELECT id INTO v_bob_id FROM users WHERE username = 'bob' LIMIT 1;

    -- Generate a sample embedding (in production, these come from OpenAI API)
    -- This is a random vector for demonstration purposes
    v_sample_embedding := array_fill(0.0, ARRAY[1536])::vector(1536);

    -- Sample semantic memories
    INSERT INTO semantic_memories (user_id, collection_name, key, text, description, embedding_id, additional_metadata)
    VALUES
        (v_alice_id, 'project_docs', 'readme_overview',
         'This project implements a Semantic Kernel application with PostgreSQL database, Docker containers, and AI capabilities.',
         'Project README overview',
         'qdrant_vector_001',
         '{"source": "README.md", "section": "overview", "last_updated": "2024-01-15"}'::jsonb),
        (v_alice_id, 'project_docs', 'architecture_summary',
         'The architecture consists of microservices including frontend (React), backend (ASP.NET Core), engine (Semantic Kernel), and database (PostgreSQL).',
         'System architecture description',
         'qdrant_vector_002',
         '{"source": "ARCHITECTURE.md", "section": "components"}'::jsonb),
        (v_alice_id, 'learning_notes', 'semantic_kernel_intro',
         'Semantic Kernel is an SDK that enables integration of Large Language Models with conventional programming languages.',
         'Introduction to Semantic Kernel',
         'qdrant_vector_003',
         '{"category": "learning", "topic": "semantic-kernel", "confidence": 0.95}'::jsonb),
        (v_bob_id, 'code_snippets', 'auth_service_pattern',
         'Authentication service pattern: Use bcrypt for password hashing, JWT for tokens, and implement refresh token rotation.',
         'Authentication best practices',
         'qdrant_vector_004',
         '{"language": "csharp", "pattern": "authentication", "security_level": "high"}'::jsonb),
        (v_bob_id, 'code_snippets', 'database_migration_pattern',
         'Database migrations should be versioned, idempotent, and include rollback procedures. Use tools like Flyway or Entity Framework migrations.',
         'Database migration strategies',
         'qdrant_vector_005',
         '{"technology": "database", "pattern": "migrations", "tools": ["flyway", "ef-core"]}'::jsonb);

    -- Sample embeddings table data (with actual vector data)
    -- Note: In production, these vectors would be generated by OpenAI embedding model
    INSERT INTO embeddings (user_id, collection_name, content_hash, text, metadata, embedding, model)
    VALUES
        (v_alice_id, 'documents', md5('semantic_kernel_concepts'),
         'Semantic Kernel allows developers to orchestrate AI models with plugins, planners, and memory systems.',
         '{"type": "concept", "tags": ["semantic-kernel", "ai", "orchestration"]}'::jsonb,
         v_sample_embedding,
         'text-embedding-3-small'),
        (v_alice_id, 'documents', md5('docker_best_practices'),
         'Docker best practices: Use multi-stage builds, minimize layers, use Alpine Linux for smaller images, and implement health checks.',
         '{"type": "best-practice", "tags": ["docker", "containers", "devops"]}'::jsonb,
         v_sample_embedding,
         'text-embedding-3-small'),
        (v_bob_id, 'code_knowledge', md5('csharp_async_patterns'),
         'C# async/await patterns: Always use ConfigureAwait(false) in libraries, avoid async void except for event handlers, use Task.WhenAll for parallel operations.',
         '{"type": "code-pattern", "language": "csharp", "tags": ["async", "best-practices"]}'::jsonb,
         v_sample_embedding,
         'text-embedding-3-small'),
        (v_bob_id, 'code_knowledge', md5('postgresql_performance'),
         'PostgreSQL performance tuning: Create indexes on foreign keys, use EXPLAIN ANALYZE to check query plans, implement connection pooling with pgBouncer.',
         '{"type": "performance", "database": "postgresql", "tags": ["optimization", "indexing"]}'::jsonb,
         v_sample_embedding,
         'text-embedding-3-small');

    RAISE NOTICE '✓ Created % semantic memories', (SELECT COUNT(*) FROM semantic_memories);
    RAISE NOTICE '✓ Created % embeddings with vector data', (SELECT COUNT(*) FROM embeddings);
    RAISE NOTICE '⚠ Sample embeddings use placeholder vectors - integrate with Qdrant for production';
END $$;
